services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: sqlite
      DB_HOST: /app/database/database.sqlite
      DB_DATABASE: /app/database/database.sqlite

  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
