services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./laravel:/app
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: sqlite
      DB_HOST: /app/database/database.sqlite
      DB_DATABASE: /app/database/database.sqlite

  angular:
    # platform: linux/amd64
    build:
      context: ./angular
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./angular:/usr/src/app
    ports:
      - "4200:4200"
