services:

  laravel:
    image: orpimel/project-laravel:1.0
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: sqlite
      DB_HOST: /app/database/database.sqlite
      DB_DATABASE: /app/database/database.sqlite

  angular:
    image: orpimel/project-angular:1.0
    restart: always
    ports:
      - "4200:4200"
